# Generated by Django 4.0.1 on 2022-02-23 08:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('empresa', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('empleo_solicitado', models.CharField(max_length=100)),
                ('requisitos', models.TextField()),
                ('imagen', models.ImageField(null=True, upload_to='solicitudes')),
                ('titulo_imagen', models.CharField(max_length=100)),
                ('sueldo', models.FloatField()),
                ('horarios', models.DateField(default=datetime.date.today)),
                ('informacion', models.TextField()),
                ('fecha_creacion', models.DateField(default=datetime.date.today)),
                ('enlace_formulario', models.URLField()),
            ],
        ),
    ]
