# Generated by Django 4.0.1 on 2022-03-01 20:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appocc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='solicitudes')),
                ('titulo_imagen', models.CharField(max_length=100)),
                ('informacion', models.TextField()),
                ('fecha_creacion', models.DateField(default=datetime.date.today)),
                ('enlace_informacion', models.URLField()),
            ],
        ),
    ]
