# Generated by Django 4.0.1 on 2022-03-23 08:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appocc', '0002_noticias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('comentarios', models.TextField()),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='Inovaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_inovacion', models.CharField(max_length=100)),
                ('empresa', models.CharField(max_length=100)),
                ('imagen', models.ImageField(null=True, upload_to='Inovaciones')),
                ('titulo_imagen', models.CharField(max_length=100)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('informacion', models.TextField()),
                ('fecha_creacion', models.DateField(default=datetime.date.today)),
                ('enlace_video', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='noticias',
            name='imagen',
            field=models.ImageField(upload_to='noticias'),
        ),
    ]
