# Generated by Django 4.0.1 on 2022-04-23 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appocc', '0004_rename_informacion_solicitud_años_experiencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='años_experiencia',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='edad',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='telefono',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
