# Generated by Django 4.0.1 on 2022-04-24 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appocc', '0005_alter_solicitud_años_experiencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='website',
            field=models.URLField(max_length=150, null=True),
        ),
    ]
